#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to
#your load-balancer IP (lb-01).
display_info() {
    local subdomain=$1
    local record_type=$2
    local destination=$3
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

audit_domain() {
    local domain=$1
    local subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        record_type=$(dig +short -t A $subdomain.$domain | awk '{print "A"}')
        destination=$(dig +short $subdomain.$domain)

        [ -n "$destination" ] && display_info "$subdomain" "$record_type" "$destination"
    done
}

main() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        audit_domain "$domain"
    else
        record_type=$(dig +short -t A $subdomain.$domain | awk '{print "A"}')
        destination=$(dig +short $subdomain.$domain)

        [ -n "$destination" ] && display_info "$subdomain" "$record_type" "$destination"
    fi
}

# Check if the required arguments are provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

main "$@"
