#!/usr/bin/env bash
# Display information about subdomains.

domain_information () {
    local domain="$1"
    local subdomain="$2"

    local line
    line=$(dig "${subdomain}.${domain}" +short | awk '{printf "%s ", $0}')
    
    if [ -n "$line" ]; then
        echo "The subdomain ${subdomain} is a ${line}record and points to ${line}"
    else
        echo "No information found for subdomain ${subdomain}"
    fi
}

if [ "$#" == 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        domain_information "$1" "${subdomain}"
    done
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
