#!/usr/bin/env bash

# Check the number of params
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Check the exit status of scp
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
else
    echo "Failed to transfer the file"
fi
