#!/usr/bin/env bash

#!/bin/bash

# Update package list and install nginx
apt-get update
apt-get install -y nginx

# Create a custom Nginx configuration for redirection
cat > /etc/nginx/sites-available/default << EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = /redirect_me {
        return 301 http://your-redirected-url;
    }
}
EOL

service nginx restart

