#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

# Update the package list and install Nginx
apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

sed -i '/server_name _;/ {
        a\rewrite ^\/redirect_me https:\/\/github.com\/alban-okoby permanent;\n
        a\error_page 404 \/custom_404.html;\n
        a\location = \/custom_404.html {\n
        a\troot \/usr\/share\/nginx\/html;\n
        a\tinternal;\n
        a}\n
    }' /etc/nginx/sites-available/default

sed -i '/include \/etc\/nginx\/sites-enabled\/\*;/ {
        a\    add_header X-Served-By "$HOSTNAME";\n
    }' /etc/nginx/nginx.conf

service nginx start
