#!/usr/bin/env bash
# MySQL backup

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
database_user="root"
database_password="$1"

mysqldump --all-databases -u "$database_user" --password="$database_password" > backup.sql
tar -czvf "$file_name" backup.sql
rm backup.sql
