#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 8 ]
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  
  (( counter++ ))
done
