#!/usr/bin/env bash

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
echo -e "server {\n\tlisten 8080 default_server;\n\tlisten [::]:8080 default_server ipv6only=on;\n\troot /var/www/html;\n\tindex index.html index.htm;\n\tserver_name _;\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}" > /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
systemctl restart nginx
