#!/bin/bash

# Check if the key pair already exists
if [ -f ~/.ssh/school ]; then
    echo "RSA key pair 'school' already exists."
    exit 1
fi

# Create RSA key pair with passphrase
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty"

echo "RSA key pair 'school' created successfully."
